---
# Cloudera playbook
- name: Configuring and Installing necessary tools
  hosts: all
  roles:
   -  pckgs
  tags: abc

- name: Configure Cloudera Manager Repository
  hosts: all 
  roles:
    - cm_repo
  tags: cm_repo

- name: Install rngd
  hosts: all
  roles:
    - rngd
  tags: rngd

- name: Install Java
  hosts: cloudera_managers
  roles:
    - java
  tags: java

- name: Install MariaDB and create databases
  hosts: cloudera_managers
  roles:
    - mariadb
  tags: mysql

- name: Install MySQL Connector
  hosts: all
  roles:
    - mysql_connector
  tags: mysql

#- name: Install MIT KDC Server
#  hosts: krb5_server
#  roles:
#    - { role: krb5_server, when: krb5_kdc_type == 'mit' }
#  tags: krb5

- name: Configure EPEL Repository
  hosts: cloudera_managers
  roles:
    - epel
  tags: epel

- name: Install Cloudera Manager Agents
  hosts: all
  roles:
    - cm_agents
  tags: cm_agents

- name: Install Cloudera Manager Server
  hosts: cloudera_managers
  roles:
    - scm
  tags: cluster_template

- name: Install CDH
  hosts: cloudera_managers
  roles:
    - cdh
  tags: cluster_template

