---

- name: Add Cloudera Manager yum repository
  yum_repository:
    name: Cloudera_manager
    description: Cloudera manager
    baseurl: https://archive.cloudera.com/cm6/6.0.1/redhat7/yum/
    gpgkey: https://archive.cloudera.com/cm6/6.0.1/redhat7/yum/RPM-GPG-KEY-cloudera
    gpgcheck: 1
    enabled: 1
  when: (ansible_distribution|lower == "redhat") or (ansible_distribution|lower == "centos")


